### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by apolkosnik-old** [blackthorne/Codetective#2]
Hi,
I wanted to ask if it's ok to put a copy of your codetective.py (unaltered in any way) file in another project. 
My first try was to just include a link to your repo, but it seems that the maintainers of that project don't want to see git repos coliding or something.

I didn't see the license file in your repo, but then the **license** in codetective.py says GPL... So, I just thought I'll ask.

Thanks in advance.

**Comment by blackthorne** [comment]
Hello Adam,
please go ahead and look out for new releases ;)

may I know what is this being used for? 

Thank you,
Kind regards,
Francisco

**Comment by apolkosnik-old** [comment]
Francisco, 
Thanks a bunch!
My plan is to incorporate it into a plugin for CRITs (https://crits.github.io/)

Best regards,
Adam
